[package]
name = "nonogram"
version = "0.1.0"
authors = ["Joe Grosspietsch <joe.grosspietsch@gmail.com>"]
edition = "2018"

[dependencies]
crc = "^1.0.0"
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
rand = "0.6"
