[package]
name = "nonogram"
version = "0.1.0"
description = "Nonogram generation and solution package"
authors = ["Joe Grosspietsch <joe.grosspietsch@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
crc = "^1.0.0"
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
rand = "0.6"
